### ISSUE TITLE
Can't build on Windows 11

### ISSUE THREAD

**Issue by sstock2005** [microsoft/BitNet#100]
Followed steps on README, result:
```
(bitnet-cpp) C:\Users\sstoc\OneDrive\bitnet\BitNet>python setup_env.py --hf-repo HF1BitLLM/Llama3-8B-1.58-100B-tokens -q i2_s
INFO:root:Compiling the code using CMake.
ERROR:root:Error occurred while running command: Command '['cmake', '-B', 'build', '-DBITNET_X86_TL2=ON', '-T', 'ClangCL']' returned non-zero exit status 1., check details in logs\generate_build_files.log

(bitnet-cpp) C:\Users\sstoc\OneDrive\bitnet\BitNet>cat logs\generate_build_files.log
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Unix Makefiles

  does not support toolset specification, but toolset

    ClangCL

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by grctest** [comment]
I got it working on windows 11 by installing visual studio community 2022, it required modifying the install with the following extensions:

![Image](https://github.com/user-attachments/assets/754894bd-e4d4-481d-ac43-ab6567819101)

And on the right tick clang:
![Image](https://github.com/user-attachments/assets/a8b4e1d3-03a7-4972-a97a-e8ff25a6f367)

After doing that & installing conda I was able to build on windows 11

**Comment by AFKMUDS** [comment]
I did this initially and auto clock isnt working while trying to build, so then I tried to not use clang and just use msvc and its just not
