### ISSUE TITLE
On Ubuntu System getting error while command executing - python setup_env.py -md models/Llama3-8B-1.58-100B-tokens -q i2_s

### ISSUE THREAD

**Issue by mrunal77** [microsoft/BitNet#103]
I am trying to run below command on Ubuntu system following documentation.
**python setup_env.py --hf-repo HF1BitLLM/Llama3-8B-1.58-100B-tokens -q i2_s**

which is throwing below error while execution

INFO:root:Converting HF model to GGUF format...
ERROR:root:Error occurred while running command: Command '['/home/mrunal/anaconda3/envs/bitnet-cpp/bin/python', 'utils/convert-hf-to-gguf-bitnet.py', 'models/Llama3-8B-1.58-100B-tokens', '--outtype', 'f32']' died with <Signals.SIGKILL: 9>., check details in logs/convert_to_f32_gguf.log

log File
[convert_to_f32_gguf.log](https://github.com/user-attachments/files/17608764/convert_to_f32_gguf.log)

how to resolve this issue please provide any suggestion.

System details
processor : i7 4790K
gpu: gtx 970

**Comment by geoej** [comment]
Are you monitoring memory? Lack of enough RAM proved to be the issue for me.

**Comment by mrunal77** [comment]
Thanks @geoej I am also facing a lack of enough RAM while compiling.
Is there any minimum RAM requirement for performing the conversion, I am currently trying with 16 gigs of RAM.

**Comment by geoej** [comment]
I think 16 gigs is not enough. you will need at least 32. also increase swap space

**Comment by kth8** [comment]
You can try running BitNet in a precompiled Docker container if you don't have enough resources on your local computer.

**Comment by phken91** [comment]
> You can try running BitNet in a precompiled Docker container if you don't have enough resources on your local computer.

hi @kth8, can you share the docker container link? i can't found it on docker hub with keyword `bitnet`

**Comment by kth8** [comment]
Someone created an issue here about running in Docker when BitNet.cpp was first released, there are instructions in there.
