### ISSUE TITLE
How to install on Mac?

### ISSUE THREAD

**Issue by anu43** [microsoft/BitNet#128]
Could the Linux installation be followed for Mac usage?

**Comment by Parvez-Khan-1** [comment]
I am also trying to setup on mac and getting below error while building the project:

``` python setup_env.py -md /models/Llama3-8B-1.58-100B-tokens -q i2_s ```

FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

**Comment by bilelouahmed** [comment]
@Parvez-Khan-1 I had the same issue that I resolved with the following command : `brew install cmake`

**Comment by seohyunjun** [comment]
```
BitNet/src/ggml-bitnet-lut.cpp:70:131: warning: unused parameter 'dst' [-Wunused-parameter]
   70 | size_t ggml_bitnet_mul_mat_get_wsize(const struct ggml_tensor * src0, const struct ggml_tensor * src1, const struct ggml_tensor * dst) {
      |                                                                                                                                   ^
45 warnings and 1 error generated.
make[2]: *** [3rdparty/llama.cpp/ggml/src/CMakeFiles/ggml.dir/__/__/__/__/src/ggml-bitnet-lut.cpp.o] Error 1
make[1]: *** [3rdparty/llama.cpp/ggml/src/CMakeFiles/ggml.dir/all] Error 2
make: *** [all] Error 2
```
I have another cmake issue. How do you resolve it? @bilelouahmed

**Comment by anu43** [comment]
> [@Parvez-Khan-1](https://github.com/Parvez-Khan-1) I had the same issue that I resolved with the following command : `brew install cmake`

thanks for the advice! it works.

@seohyunjun you should be fine by following the README steps but let me share it once again.

```
git clone --recursive https://github.com/microsoft/BitNet.git
cd BitNet

# (Recommended) Create a new conda environment
conda create -n bitnet-cpp python=3.9
conda activate bitnet-cpp # Be sure that you activate your environment

pip install -r requirements.txt

python setup_env.py --hf-repo HF1BitLLM/Llama3-8B-1.58-100B-tokens -q i2_s

python run_inference.py -m models/Llama3-8B-1.58-100B-tokens/ggml-model-i2_s.gguf -p "Daniel went back to the the the garden. Mary travelled to the kitchen. Sandra journeyed to the kitchen. Sandra went to the hallway. John went to the bedroom. Mary went back to the garden. Where is Mary?\nAnswer:" -n 6 -temp 0
```

**Comment by seohyunjun** [comment]
@anu43  Thank you guide for me, unfortunetely my cmake build condition is not work.

i have another issue... 

Anyway have good day
