### ISSUE TITLE
Quantisation

### ISSUE THREAD

**Issue by lfoppiano** [microsoft/BitNet#129]
I'm trying to run on bitnet a fine-tuned model of `Llama3-8B-1.58-100B-tokens`. The model was already quantized dynamically, however it seems mandatory to convert the model to the gguf model format. Let me know if you think I'm doing something wrong. 

Looking at the table [here](https://github.com/microsoft/BitNet?tab=readme-ov-file#supported-models), it seems that for running the `Llama3-8B-1.58-100B-tokens` model on arm is necessary to quantize using `tl2`, however, when I try to run the `setup_env.py` I get this: 

```
usage: setup_env.py [-h] [--hf-repo {1bitLLM/bitnet_b1_58-large,1bitLLM/bitnet_b1_58-3B,HF1BitLLM/Llama3-8B-1.58-100B-tokens}]
                    [--model-dir MODEL_DIR] [--log-dir LOG_DIR] [--quant-type {i2_s,tl1}] [--quant-embd] [--use-pretuned]
setup_env.py: error: argument --quant-type/-q: invalid choice: 'tl2' (choose from 'i2_s', 'tl1')
```

so is it possible to use tl2 for quantization?

**Comment by potassiummmm** [comment]
Please check the table again, it should be tl1.

**Comment by lfoppiano** [comment]
OK. Thanks for clarifying.

The table is not easy to read on a dark theme, because the X appear more prominent than the V.
