### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Loksly** [microsoft/BitNet#19]
hi! 

this looks awesome.

Would you consider the possibility of providing a Docker image so it's easier to test and deploy? 

Thanks for this anyway

**Comment by kth8** [comment]
Here is a Dockerfile I wrote to get it to run, image is about 4.9GB:
```
FROM python:3.9-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y cmake clang git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --recursive --depth 1 https://github.com/microsoft/BitNet.git && \
    rm -rf BitNet/.git

WORKDIR /BitNet

RUN pip install -r requirements.txt && \
    pip cache purge

RUN python3 utils/codegen_tl2.py --model Llama3-8B-1.58-100B-tokens --BM 256,128,256,128 --BK 96,96,96,96 --bm 32,32,32,32

RUN cmake -B build -DBITNET_X86_TL2=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

RUN cmake --build build --target llama-cli --config Release

ADD https://huggingface.co/brunopio/Llama3-8B-1.58-100B-tokens-GGUF/resolve/main/Llama3-8B-1.58-100B-tokens-TQ2_0.gguf .

RUN echo "2565559c82a1d03ecd1101f536c5e99418d07e55a88bd5e391ed734f6b3989ac  Llama3-8B-1.58-100B-tokens-TQ2_0.gguf" | shasum -ca 256

CMD ["python3", "run_inference.py", "-m", "Llama3-8B-1.58-100B-tokens-TQ2_0.gguf", "-temp", "0", "-p", "The sky is blue due to a phenomenon called"]
```

**Comment by kth8** [comment]
with alpine it saves 700MB of space:
```
FROM python:3.9-alpine
RUN apk add --no-cache build-base cmake clang git && \
    rm -rf /var/cache/apk/*

RUN git clone --recursive --depth 1 https://github.com/microsoft/BitNet.git && \
    rm -rf BitNet/.git

WORKDIR /BitNet

RUN pip install -r requirements.txt && \
    pip cache purge

RUN python3 utils/codegen_tl2.py --model Llama3-8B-1.58-100B-tokens --BM 256,128,256,128 --BK 96,96,96,96 --bm 32,32,32,32

RUN cmake -B build -DBITNET_X86_TL2=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

RUN cmake --build build --target llama-cli --config Release

ADD https://huggingface.co/brunopio/Llama3-8B-1.58-100B-tokens-GGUF/resolve/main/Llama3-8B-1.58-100B-tokens-TQ2_0.gguf .

RUN echo "2565559c82a1d03ecd1101f536c5e99418d07e55a88bd5e391ed734f6b3989ac Llama3-8B-1.58-100B-tokens-TQ2_0.gguf" | sha256sum -c

CMD ["python3", "run_inference.py", "-m", "Llama3-8B-1.58-100B-tokens-TQ2_0.gguf", "-p", "The sky is blue due to a phenomenon called"]
```

**Comment by kth8** [comment]
I decided to publish a Docker image based on that Dockerfile to more easily test it https://github.com/kth8/bitnet

**Comment by stackblogger** [comment]
I created a Node.Js Web UI with Socket implementation using your Docker image. Anyone looking to play with this LLM from a web interface can setup this containerised application in a Linux environment. https://github.com/stackblogger/bitnet.js

**Comment by Deng-Xian-Sheng** [comment]
ollama?

**Comment by grigio** [comment]
@kth8 Thanks the Dockerfile with Alpine works fine.. The model is fast but it writes a lot of nonsense

**Comment by kth8** [comment]
@grigio 

The current models available are research models and not instruct models so they won't give you answer like you are used to but instead act like autocompletes.

**Comment by ozbillwang** [comment]
> with alpine it saves 700MB of space:
> 
> ```
> FROM python:3.9-alpine
> RUN apk add --no-cache build-base cmake clang git
> 
> RUN git clone --recursive --depth 1 https://github.com/microsoft/BitNet.git && \
>     rm -rf BitNet/.git
> 
> WORKDIR /BitNet
> 
> RUN pip install --no-cache-dir -r requirements.txt
> 
> RUN python3 utils/codegen_tl2.py --model Llama3-8B-1.58-100B-tokens --BM 256,128,256,128 --BK 96,96,96,96 --bm 32,32,32,32
> 
> RUN cmake -B build -DBITNET_X86_TL2=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
> 
> RUN cmake --build build --target llama-cli --config Release
> 
> ADD https://huggingface.co/brunopio/Llama3-8B-1.58-100B-tokens-GGUF/resolve/main/Llama3-8B-1.58-100B-tokens-TQ2_0.gguf .
> 
> RUN echo "2565559c82a1d03ecd1101f536c5e99418d07e55a88bd5e391ed734f6b3989ac Llama3-8B-1.58-100B-tokens-TQ2_0.gguf" | sha256sum -c
> 
> CMD ["python3", "run_inference.py", "-m", "Llama3-8B-1.58-100B-tokens-TQ2_0.gguf", "-p", "The meaning to life and the universe is"]
> ```

should we build the application only in the image, then mount the llm later?

**Comment by kth8** [comment]
@ozbillwang The image is just for demo purposes so requiring a host mount will add complexity considering all the various platforms people could run Docker on. Including everything needed to run in 1 image makes things as simple as possible.

**Comment by vak** [comment]
btw, @kth8's alpine image also works well with `python:3.12-alpine`. 
(However not yet with python:alpine, because it is based on Python 3.13)

Althogh the performance (i.e. the token throughput) under both python 3.9 and python 3.12 is the same.

**Comment by ozbillwang** [comment]
> btw, @kth8's alpine image also works well with `python:3.12-alpine`. 
> (However not yet with python:alpine, because it is based on Python 3.13)
> 
> Althogh the performance (i.e. the token throughput) under both python 3.9 and python 3.12 is the same.

really? i worked it out only with python 3.11.

**Comment by vak** [comment]
@ozbillwang yep.

the only change I needed:
```
#FROM python:3.9-alpine
FROM python:3.12-alpine
```
This did a switch to Python 3.12.7

Here is the throughput on my desktop PC (as said, it is  the same as for Python 3.9 though) :

```
...
sampler seed: 1846266218
sampler params:
	repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
	top_k = 40, tfs_z = 1.000, top_p = 0.950, min_p = 0.050, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampler chain: logits -> logit-bias -> penalties -> top-k -> tail-free -> typical -> top-p -> min-p -> temp-ext -> softmax -> dist
generate: n_ctx = 2048, n_batch = 1, n_predict = 128, n_keep = 1

The meaning to life and the universe is not a matter of chance. It is a matter of the will of God. It was the will of God that there should be a universe, and it is the will of God that this universe should not be without life. God is the source of all life, and therefore He is the source of all that is good, and therefore good is not a matter of chance. God is the source of all the good, and therefore God is the source of all the beautiful, the true, the lovely, the just, the good, and the true. It is the will of God that all men should be saved. It is the will

llama_perf_sampler_print:    sampling time =       7.25 ms /   137 runs   (    0.05 ms per token, 18886.13 tokens per second)
llama_perf_context_print:        load time =     609.15 ms
llama_perf_context_print: prompt eval time =     709.52 ms /     9 tokens (   78.84 ms per token,    12.68 tokens per second)
llama_perf_context_print:        eval time =    9956.22 ms /   127 runs   (   78.40 ms per token,    12.76 tokens per second)
```

**Comment by clod81** [comment]
anyone had it running on arm cpu? (aarch64 for the container)

**Comment by jameerjkt** [comment]
> anyone had it running on arm cpu? (aarch64 for the container)

Yes. I built one named [`BitNet-Stack`](https://github.com/stackblogger/BitNet-Stack) that runs on aarch64 CPU. It provides a web UI to interact with BitNet and streams the response word by word, similar to ChatGPT.

It provides one single Docker command to run the LLM and UI. It supports conversational response. You can chat with the LLM where it remembers the context.
