### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by sean-jang00** [microsoft/BitNet#41]
![Image](https://github.com/user-attachments/assets/cfabcaa5-5a30-4625-be09-853c8d3fee95)

The difference in memory usage between the LLaMA LLM model and BitNet B1.58 doesn't seem as large as expected, even though they have the same number of parameters. If the LLaMA LLM uses 16-bit precision weights and BitNet uses 1.58-bit weights, the memory usage for LLaMA should be at least 8 times higher. Why is the difference in usage smaller?

**Comment by sean-jang00** [comment]
I was only focusing on the weights, but I should also consider the memory space used for activations. Since the activations in BitNet B1.58 are 8-bit, the memory savings for internal activations will be limited to 2x. The KV cache is also 8-bit, so the memory savings in that area should also be calculated as 2x.
I would like the author to confirm my assumptions.

**Comment by shumingma** [comment]
The KV cache and the embeddings remain in full precision. For a smaller-size model, they take up a larger proportion of the memory.

**Comment by sean-jang00** [comment]
@shumingma  Thanks for the clarification.
