### ISSUE TITLE
how to generate a dummy modelQwen models

### ISSUE THREAD

**Issue by summerHearts** [microsoft/BitNet#52]
Traceback (most recent call last):
  File "/BitNet/utils/generate-dummy-bitnet-model.py", line 1048, in <module>
    main()
  File "BitNet/utils/generate-dummy-bitnet-model.py", line 971, in main
    model_class = Model.from_model_architecture(hparams["architectures"][0])
  File "BitNet/utils/generate-dummy-bitnet-model.py", line 312, in from_model_architecture
    raise NotImplementedError(f'Architecture {arch!r} not supported!') from None
NotImplementedError: Architecture 'Qwen2ForCausalLM' not supported!
![Image](https://github.com/user-attachments/assets/dd7a9dfa-c6ec-4a54-bd89-c217d0a47c66)

How should I handle it，thanks

**Comment by masembebrian** [comment]
Check Compatibility: Ensure that the model architecture you're trying to use is supported in BitNet. Review the **model** class or BitNet documentation for supported architectures.

Update or Modify: If Qwen2ForCausalLM is not supported, you might need to modify the code to use a supported architecture or contribute by adding support if needed.
