### ISSUE TITLE
error while executing python setup_env.py -md models/Llama3-8B-1.58-100B-tokens -q i2_s command

### ISSUE THREAD

**Issue by HariKrishna070** [microsoft/BitNet#62]
I am trying to runt he following command in my system(Windows 11) :

python setup_env.py -md models/Llama3-8B-1.58-100B-tokens -q i2_s

 and I am getting the following error : 

################################

INFO:root:Compiling the code using CMake.
ERROR:root:Error occurred while running command: Command '['cmake', '-B', 'build', '-DBITNET_X86_TL2=ON', '-T', 'ClangCL']' returned non-zero exit status 1., check details in logs\generate_build_files.log

################################

I have this versions installed in my conda environment

################################
python - 3.9.20
cmake - 3.29.2
clang - 19.1.2
################################

How to resolve this?

**Comment by rodyherrera** [comment]
Check [https://github.com/microsoft/BitNet/issues/25#issuecomment-2426882861](https://github.com/microsoft/BitNet/issues/25#issuecomment-2426882861)

**Comment by thuyduong19062004** [comment]
I get the same error.

**Comment by dinhvanlinh0610** [comment]
I also got the same error

**Comment by to-grt** [comment]
Can you show us the logs\generate_build_files.log ?

**Comment by dinhvanlinh0610** [comment]
logs\generate_build_files.log

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045. 
CMake Error at CMakeLists.txt:2 (project): 
  Failed to run MSBuild command: 
 
    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe 
 
  to get the value of VCTargetsPath: 
 
    MSBuild version 17.9.8+b34f75857 for .NET Framework 
    Build started 10/22/2024 5:19:53 PM. 
     
    Project "C:\Users\Admin\Downloads\Code\BitNet\build\CMakeFiles\3.30.5\VCTargetsPath.vcxproj" on node 1 (default targets). 
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Admin\Downloads\Code\BitNet\build\CMakeFiles\3.30.5\VCTargetsPath.vcxproj] 
    Done Building Project "C:\Users\Admin\Downloads\Code\BitNet\build\CMakeFiles\3.30.5\VCTargetsPath.vcxproj" (default targets) -- FAILED. 
     
    Build FAILED. 
     
    "C:\Users\Admin\Downloads\Code\BitNet\build\CMakeFiles\3.30.5\VCTargetsPath.vcxproj" (default target) (1) -> 
    (PrepareForBuild target) ->  
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Admin\Downloads\Code\BitNet\build\CMakeFiles\3.30.5\VCTargetsPath.vcxproj] 
     
        0 Warning(s) 
        1 Error(s) 
     
    Time Elapsed 00:00:00.91 
     
 
  Exit code: 1 
 
 
 
-- Configuring incomplete, errors occurred!

**Comment by to-grt** [comment]
It seems like clang is not detected in your installation : 
`The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found.`
I am not sure how you installed it but I strongly suggest you follow the instructions given in the README:
![Image](https://github.com/user-attachments/assets/ece72e26-38ff-41e3-aeab-9ffc494a59f6)
If this is how you did it, I don't know where I could have gone wrong. Are you using one of these?
![Image](https://github.com/user-attachments/assets/400d7cd6-3f21-4e38-bd73-c8afd81cc30f)

**Comment by antonovkz** [comment]
> It seems like clang is not detected in your installation : `The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found.` I am not sure how you installed it but I strongly suggest you follow the instructions given in the README: ![Image](https://github.com/user-attachments/assets/ece72e26-38ff-41e3-aeab-9ffc494a59f6) If this is how you did it, I don't know where I could have gone wrong. Are you using one of these? ![Image](https://github.com/user-attachments/assets/400d7cd6-3f21-4e38-bd73-c8afd81cc30f)

Yes, I tried to do it from under it, the same error, I even tried to activate C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build>vcvars64.bat before that. I get this error

```
IINFO:root:Compiling the code using CMake.
ERROR:root:Error occurred while running command: Command '['cmake', '-B', 'build', '-DBITNET_X86_TL2=ON', '-T', 'ClangCL']' returned non-zero exit status 1., check details in logs\generate_build_files.log
```

**Comment by to-grt** [comment]
And do you have the same log output as shown before?

**Comment by to-grt** [comment]
Try:
`export CC=/usr/bin/clang-18
export CXX=/usr/bin/clang++-18`

**Comment by RoadTLife** [comment]
Invalid
![Image](https://github.com/user-attachments/assets/32cc5027-9f11-4d63-9718-83925a53fdc4)

**Comment by to-grt** [comment]
Last idea:
`sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100`
`sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100`
Now select the correct clang version if you have several alternatives set up:
`sudo update-alternatives --config clang`
`sudo update-alternatives --config clang++`
Verify with:
`clang --version`
`clang++ --version`
It will use clang-18 as the default alternative when anything tries to call clang. If you need clang in the future, be mindful that this version will be used.

**Comment by RoadTLife** [comment]
The command  
`sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100`
`sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100` works, thank you .
