### ISSUE TITLE
Memory leak in quantize_i2_s function

### ISSUE THREAD

**Issue by asalaria-cisco** [microsoft/BitNet#70]
Looking at the source code of `quantize_i2_s `, it seems that the buffer `q8` is [allocated on the heap](https://github.com/microsoft/BitNet/blob/a97dfe458afdf79831884d1928fb9f23f16d270b/src/ggml-bitnet-mad.cpp#L60C5-L60C57) but never freed. This would results in leaking memory each time the function is called.

**Comment by Mujahid087** [comment]
**yes you are right **

**Comment by paaspaas00** [comment]
#54
