### ISSUE TITLE
readme steps don't work for me. Fails at setup_env.py

### ISSUE THREAD

**Issue by byjlw** [microsoft/BitNet#73]
`(.venv) PS C:\Users\jesse\Documents\source\BitNet> python setup_env.py --hf-repo HF1BitLLM/Llama3-8B-1.58-100B-tokens -q
 i2_s`

```
Traceback (most recent call last):
  File "C:\Users\jesse\Documents\source\BitNet\setup_env.py", line 202, in <module>
    main()
  File "C:\Users\jesse\Documents\source\BitNet\setup_env.py", line 179, in main
    compile()
  File "C:\Users\jesse\Documents\source\BitNet\setup_env.py", line 163, in compile
    cmake_exists = subprocess.run(["cmake", "--version"], capture_output=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by antonovkz** [comment]
Same

**Comment by bmerkle** [comment]
please make sure that in your build environment cmake is installed+in the path.
also assert that it matches the required version from readme (3.22)

there is a issue https://github.com/microsoft/BitNet/issues/34 + PR for this problem already.

**Comment by bmerkle** [comment]
i first start the Developer Command Prompt for VS 2022
then i check cmake and clang (see screenshot)

![Image](https://github.com/user-attachments/assets/bf94b39b-15f6-42e6-afd7-45e8f141e1d1)

then i start conda
conda activate bitnet-cpp

From your logoutput Command '['cmake', '-B', 'build', '-DBITNET_X86_TL2=ON', '-T', '**ClangCL**']' 
I can see that you are using ClangCL 
ClangCL is the Clang compiler with a command-line interface compatible with Microsoft’s cl.exe (MSVC) compiler, which allows it to be used in environments typically meant for Visual Studio.

So please make sure that the Visual Studio clang compiler version is visible and installed:

(bitnet-cpp) C:\work\microsoft\BitNet>clang --version
clang version 17.0.3
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\Llvm\bin

**Comment by byjlw** [comment]
Wait this project only works if you are using Visual Studio 2022? It doesn't work at all outside of it, like VSCode?

**Comment by bmerkle** [comment]
it is C/C++ code. You have to build and compile it with a compiler (e.g. clang or clang from Visual Studio).

you should check the README :-) https://github.com/microsoft/BitNet?tab=readme-ov-file#installation

**Comment by byjlw** [comment]
Let me clarify. Do i have to buy Visual studio Pro to use this library or can i use clang and CMAKE directly?
I read the readme. I don't want to buy visual studio and have clang and CMAKE installed on my machine, so i can't follow the steps to the T.

**Comment by grctest** [comment]
I used the community version of visual studio, needed to add 2 extensions to enable building, then used conda and followed the readme.

I got similar errors to you when I tried using vs code insiders & venv

Now it works for me
