### ISSUE TITLE
File utils/kernel_tuning.py not used.

### ISSUE THREAD

**Issue by Gabrielfernandes7** [microsoft/BitNet#91]
Could you help us understan why this file is empty and what its relevence is to the project?

**Comment by sd983527** [comment]
it is for a future update, that support further tuning of the parameters in block size. we will put it out once it is ready. thanks.

**Comment by Gabrielfernandes7** [comment]
> it is for a future update, that support further tuning of the parameters in block size. we will put it out once it is ready. thanks.

Thanks, man! 👏🏽
