### ISSUE TITLE
Question. why cmake just use one core to compile, its so slow ?

### ISSUE THREAD

**Issue by YouUpDay** [microsoft/BitNet#98]
I ran this command, found its very slow, just use one core to compile the project.

python setup_env.py -md models/Llama3-8B-1.58-100B-tokens -q i2_s

then i changed the code in  setup_env.py as below, but it can't work,  what should I do? 

run_command(["cmake", "--build", "build", "--config", "Release","--parallel","200"], log_step="compile")

**Comment by potassiummmm** [comment]
Of course you can increase the speed by adding this command, but I'm curious why it doesn't work, can you show me the contents of the `logs/compile.log` file?
